# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-26 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='git_code_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u540d\u79f0')),
                ('method', models.CharField(blank=True, choices=[('web', 'web\u66f4\u65b0'), ('php_pc', 'pc\u7aefphp\u4ee3\u7801\u66f4\u65b0'), ('php_mobile', '\u624b\u673a\u7aefphp\u4ee3\u7801\u66f4\u65b0'), ('js_pc', 'pc\u7aefjs\u4ee3\u7801\u66f4\u65b0'), ('js_mobile', '\u624b\u673a\u7aefjs\u4ee3\u7801\u66f4\u65b0'), ('php', 'PHP-Pub\u4ee3\u7801\u66f4\u65b0'), ('js', 'JS-Pub\u4ee3\u7801\u66f4\u65b0'), ('config', 'PHP-Config\u66f4\u65b0')], max_length=20, null=True)),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='\u53d8\u66f4\u7248\u672c\u53f7')),
                ('branch', models.CharField(blank=True, default='main', max_length=64, verbose_name='\u53d8\u66f4\u5206\u652f')),
                ('web_branches', models.CharField(blank=True, default='main', max_length=64, verbose_name='web\u5206\u652f')),
                ('php_pc_branches', models.CharField(blank=True, default='main', max_length=64, verbose_name='php_pc\u5206\u652f')),
                ('php_mobile_branches', models.CharField(blank=True, default='main', max_length=64, verbose_name='php_mobile\u5206\u652f')),
                ('js_pc_branches', models.CharField(blank=True, default='main', max_length=64, verbose_name='js_pc\u5206\u652f')),
                ('js_mobile_branches', models.CharField(blank=True, default='main', max_length=64, verbose_name='js_mobile\u5206\u652f')),
                ('config_branches', models.CharField(blank=True, default='main', max_length=64, verbose_name='config\u5206\u652f')),
                ('web_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='web\u7248\u672c')),
                ('php_pc_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='php\u7535\u8111\u7aef')),
                ('php_moblie_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='php\u624b\u673a\u7aef')),
                ('js_pc_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='js\u7535\u8111\u7aef')),
                ('js_mobile_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='js\u624b\u673a\u7aef')),
                ('config_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='config\u7248\u672c')),
                ('last_version', models.TextField(blank=True, null=True, verbose_name='\u4e0a\u4e2a\u7248\u672c')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u53d1\u5e03\u539f\u56e0')),
                ('details', models.TextField(blank=True, null=True, verbose_name='\u66f4\u65b0\u8be6\u60c5')),
                ('isaudit', models.BooleanField(default=False, verbose_name='\u5ba1\u6838\u662f\u5426\u901a\u8fc7')),
                ('isurgent', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7d27\u6025')),
                ('islog', models.BooleanField(default=False, verbose_name='\u662f\u5426\u66f4\u65b0\u5b8c\u6210')),
                ('isuse', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5728\u4f7f\u7528\u4e2d')),
                ('execution_time', models.DateTimeField(auto_now=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ctime'],
                'verbose_name': 'git_\u66f4\u65b0\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='git_coderepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('classify', models.CharField(blank=True, choices=[('huidu', '\u7070\u5ea6'), ('online', '\u751f\u4ea7'), ('test', '\u6d4b\u8bd5')], max_length=32, null=True, verbose_name='\u73af\u5883\u7c7b\u578b')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('ispublic', models.BooleanField(default=False, verbose_name='\u662f\u5426\u516c\u7528\u5e93')),
                ('isexist', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u5b58\u5728')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='\u5730\u5740')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='\u7528\u6237')),
                ('passwd', models.CharField(blank=True, max_length=64, verbose_name='\u5bc6\u7801')),
                ('reversion', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5f53\u524d\u7248\u672c')),
                ('branch', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5f53\u524d\u5206\u652f')),
            ],
            options={
                'verbose_name': '\u4ee3\u7801\u5e93',
                'verbose_name_plural': '\u4ee3\u7801\u5e93',
            },
        ),
        migrations.CreateModel(
            name='git_deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='1001', max_length=45, verbose_name='\u540d\u79f0')),
                ('platform', models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee')], default='\u73b0\u91d1\u7f51', max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('classify', models.CharField(choices=[('huidu', '\u7070\u5ea6'), ('online', '\u751f\u4ea7'), ('test', '\u6d4b\u8bd5')], max_length=64, verbose_name='\u53d1\u5e03\u7c7b\u578b')),
                ('conf_domain', models.BooleanField(default=False, verbose_name='\u662f\u5426\u9700\u8981\u914d\u7f6e\u57df\u540d')),
                ('now_reversion', models.TextField(blank=True, null=True, verbose_name='\u5f53\u524d\u7248\u672c')),
                ('old_reversion', models.TextField(blank=True, null=True, verbose_name='\u5386\u53f2\u7248\u672c')),
                ('isdev', models.BooleanField(default=False, verbose_name='\u5f00\u53d1\u662f\u5426\u5b8c\u6210\u914d\u7f6e')),
                ('isops', models.BooleanField(default=False, verbose_name='\u8fd0\u7ef4\u662f\u5426\u5b8c\u6210\u914d\u7f6e')),
                ('isaudit', models.BooleanField(default=False, verbose_name='\u5ba1\u6838\u662f\u5426\u901a\u8fc7')),
                ('islog', models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03\u5b8c\u6210')),
                ('islock', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u9501')),
                ('usepub', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8c03\u7528\u516c\u7528\u5e93')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u5173\u8054\u4e1a\u52a1')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'git_\u53d1\u5e03\u914d\u7f6e',
                'verbose_name_plural': 'git_\u53d1\u5e03\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='git_deploy_audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee')], max_length=32, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('classify', models.CharField(choices=[('huidu', '\u7070\u5ea6'), ('online', '\u751f\u4ea7'), ('test', '\u6d4b\u8bd5')], max_length=32, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('isurgent', models.BooleanField(default=False, verbose_name='\u7d27\u6025\u5ba1\u6838')),
                ('name', models.CharField(choices=[('\u53d1\u5e03', '\u53d1\u5e03'), ('\u66f4\u65b0', '\u66f4\u65b0'), ('php\u66f4\u65b0', 'php\u66f4\u65b0')], max_length=64, verbose_name='\u540d\u79f0')),
                ('ischeck', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('start_time', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5ba1\u6838\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5ba1\u6838\u7ed3\u675f\u65f6\u95f4')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u7ba1\u7406\u5458')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='git_deploy_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('\u53d1\u5e03', '\u53d1\u5e03'), ('\u66f4\u65b0', '\u66f4\u65b0'), ('php\u66f4\u65b0', 'php\u66f4\u65b0')], max_length=45, verbose_name='\u7c7b\u578b')),
                ('log', models.TextField(blank=True, verbose_name='\u65e5\u5fd7')),
                ('update', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7c7b\u578b')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('git_deploy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_logs', to='gitfabu.git_deploy', verbose_name='\u53d1\u5e03\u9879\u76ee')),
            ],
        ),
        migrations.CreateModel(
            name='git_ops_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('\u6e90\u7ad9', '\u6e90\u7ad9'), ('AG', 'AG'), ('\u540e\u53f0', '\u540e\u53f0'), ('\u6e90\u7ad9\u53cd\u4ee3', '\u6e90\u7ad9\u53cd\u4ee3')], max_length=45, verbose_name='\u540d\u79f0')),
                ('classify', models.CharField(choices=[('huidu', '\u7070\u5ea6'), ('online', '\u751f\u4ea7'), ('test', '\u6d4b\u8bd5')], max_length=32, verbose_name='\u7c7b\u578b')),
                ('platform', models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('remoteip', models.TextField(blank=True, default='172.16.13.7', null=True, verbose_name='\u670d\u52a1\u5668ip')),
                ('remotedir', models.TextField(blank=True, default='/data/wwwroot/', null=True, verbose_name='\u76ee\u5f55')),
                ('owner', models.TextField(blank=True, default='www', null=True, verbose_name='\u5c5e\u4e3b')),
                ('exclude', models.TextField(blank=True, default='Logs/', null=True, verbose_name='\u6392\u9664\u6587\u4ef6')),
                ('rsync_command', models.TextField(blank=True, null=True, verbose_name='\u63a8\u9001\u524d\u547d\u4ee4')),
                ('last_command', models.TextField(blank=True, null=True, verbose_name='\u751f\u6548\u524d\u547d\u4ee4')),
            ],
        ),
        migrations.CreateModel(
            name='git_task_audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('isaudit', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('ispass', models.BooleanField(default=False, verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('audit_time', models.DateTimeField(auto_now=True)),
                ('postil', models.TextField(blank=True, null=True, verbose_name='\u6279\u6ce8')),
                ('loss_efficacy', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8fc7\u671f')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u4eba')),
            ],
            options={
                'ordering': ['-create_date'],
                'verbose_name': '\u4efb\u52a1\u5ba1\u6838',
                'verbose_name_plural': '\u4efb\u52a1\u5ba1\u6838',
            },
        ),
        migrations.CreateModel(
            name='my_request_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('table_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5173\u8054\u8868')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8868\u4e2d\u67d0\u5b57\u6bb5id')),
                ('memo', models.TextField(verbose_name='\u5185\u5bb9')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=64, verbose_name='\u72b6\u6001')),
                ('isend', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5b8c\u6210')),
                ('loss_efficacy', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4f5c\u5e9f')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoami', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u8d77\u4eba')),
            ],
            options={
                'ordering': ['-end_date'],
                'verbose_name': '\u6211\u53d1\u8d77\u7684\u4efb\u52a1',
                'verbose_name_plural': '\u6211\u53d1\u8d77\u7684\u4efb\u52a1',
            },
        ),
        migrations.AddField(
            model_name='git_task_audit',
            name='request_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqt', to='gitfabu.my_request_task'),
        ),
        migrations.AddField(
            model_name='git_deploy',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_dev', to='gitfabu.git_ops_configuration', verbose_name='\u670d\u52a1\u5668\u914d\u7f6e'),
        ),
        migrations.AddField(
            model_name='git_code_update',
            name='code_conf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_update', to='gitfabu.git_deploy', verbose_name='\u914d\u7f6e\u4fe1\u606f'),
        ),
    ]
