# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-22 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180122_1611'),
        ('gitfabu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='git_deploy_audit',
            options={'verbose_name': '\u5ba1\u6838\u9879\u8bbe\u7f6e', 'verbose_name_plural': '\u5ba1\u6838\u9879\u8bbe\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='git_ops_configuration',
            options={'verbose_name': '\u670d\u52a1\u5668\u914d\u7f6e', 'verbose_name_plural': '\u670d\u52a1\u5668\u914d\u7f6e'},
        ),
        migrations.AddField(
            model_name='git_deploy_audit',
            name='group',
            field=models.ManyToManyField(to='accounts.department_Mode'),
        ),
        migrations.AddField(
            model_name='git_task_audit',
            name='audit_group_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5ba1\u6838\u4eba\u6240\u5c5e\u7ec4'),
        ),
        migrations.AlterField(
            model_name='git_ops_configuration',
            name='name',
            field=models.CharField(choices=[('apiwork', 'apiwork'), ('dsf', 'dsf'), ('\u6e90\u7ad9', '\u6e90\u7ad9'), ('AG', 'AG'), ('\u540e\u53f0', '\u540e\u53f0'), ('\u6e90\u7ad9\u53cd\u4ee3', '\u6e90\u7ad9\u53cd\u4ee3')], max_length=45, verbose_name='\u540d\u79f0'),
        ),
    ]
