# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitfabu', '0002_auto_20180122_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='git_code_update',
            options={'ordering': ['-ctime'], 'verbose_name': 'git_\u66f4\u65b0\u914d\u7f6e', 'verbose_name_plural': 'git_\u66f4\u65b0\u914d\u7f6e'},
        ),
        migrations.AddField(
            model_name='my_request_task',
            name='types',
            field=models.CharField(blank=True, default='gx', max_length=64, verbose_name='\u4efb\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='git_deploy',
            name='isops',
            field=models.BooleanField(default=False, verbose_name='\u8fd0\u7ef4\u662f\u5426\u786e\u8ba4\u53d1\u5e03\u5b8c\u6210'),
        ),
        migrations.AlterField(
            model_name='git_deploy_audit',
            name='name',
            field=models.CharField(choices=[('\u53d1\u5e03', '\u53d1\u5e03'), ('\u66f4\u65b0', '\u66f4\u65b0'), ('php\u66f4\u65b0', 'php\u66f4\u65b0'), ('\u53d1\u5e03\u590d\u6838', '\u53d1\u5e03\u590d\u6838')], max_length=64, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='git_deploy_logs',
            name='name',
            field=models.CharField(choices=[('\u53d1\u5e03', '\u53d1\u5e03'), ('\u66f4\u65b0', '\u66f4\u65b0'), ('php\u66f4\u65b0', 'php\u66f4\u65b0'), ('\u53d1\u5e03\u590d\u6838', '\u53d1\u5e03\u590d\u6838')], max_length=45, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='git_ops_configuration',
            name='name',
            field=models.CharField(choices=[('apiwork', 'apiwork'), ('dsf', 'dsf'), ('\u6e90\u7ad9', '\u6e90\u7ad9'), ('AG', 'AG'), ('\u540e\u53f0', '\u540e\u53f0'), ('\u6e90\u7ad9\u53cd\u4ee3', '\u6e90\u7ad9\u53cd\u4ee3'), ('AG\u53cd\u4ee3', 'AG\u53cd\u4ee3')], max_length=45, verbose_name='\u540d\u79f0'),
        ),
    ]
