# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitfabu', '0003_auto_20180417_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git_coderepo',
            name='platform',
            field=models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee'), ('VUE\u86ee\u725b', 'VUE\u86ee\u725b')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='git_deploy',
            name='platform',
            field=models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee'), ('VUE\u86ee\u725b', 'VUE\u86ee\u725b')], default='\u73b0\u91d1\u7f51', max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='git_deploy_audit',
            name='platform',
            field=models.CharField(choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee'), ('VUE\u86ee\u725b', 'VUE\u86ee\u725b')], max_length=32, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='git_ops_configuration',
            name='platform',
            field=models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee'), ('VUE\u86ee\u725b', 'VUE\u86ee\u725b')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
    ]
