# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-12-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitfabu', '0004_auto_20180915_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git_code_update',
            name='method',
            field=models.CharField(blank=True, choices=[('web', 'web\u66f4\u65b0'), ('php_pc', 'pc\u7aefphp\u4ee3\u7801\u66f4\u65b0'), ('php_mobile', '\u624b\u673a\u7aefphp\u4ee3\u7801\u66f4\u65b0'), ('js_pc', 'pc\u7aefjs\u4ee3\u7801\u66f4\u65b0'), ('js_mobile', '\u624b\u673a\u7aefjs\u4ee3\u7801\u66f4\u65b0'), ('php', 'PHP-Pub\u4ee3\u7801\u66f4\u65b0'), ('js', 'JS-Pub\u4ee3\u7801\u66f4\u65b0'), ('vue_php', 'VUE-PHP\u66f4\u65b0'), ('vue_wap', 'VUE-\u624b\u673a\u66f4\u65b0'), ('vue_pc', 'VUE-\u7535\u8111\u66f4\u65b0'), ('config', 'PHP-Config\u66f4\u65b0')], max_length=20, null=True),
        ),
    ]
