# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2019-05-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitfabu', '0005_auto_20181204_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git_deploy_logs',
            name='update',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='git_ops_configuration',
            name='name',
            field=models.CharField(choices=[('dsf', 'dsf'), ('\u6e90\u7ad9', '\u6e90\u7ad9'), ('AG', 'AG'), ('\u540e\u53f0', '\u540e\u53f0'), ('\u6e90\u7ad9\u53cd\u4ee3', '\u6e90\u7ad9\u53cd\u4ee3'), ('AG\u53cd\u4ee3', 'AG\u53cd\u4ee3')], max_length=45, verbose_name='\u540d\u79f0'),
        ),
    ]
