# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-02 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(blank=True, max_length=128, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_type', models.CharField(blank=True, max_length=64, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('purpose', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7528\u9014')),
                ('status', models.CharField(choices=[('on', '\u7ebf\u4e0a\u4f7f\u7528'), ('wait', '\u7ebf\u4e0b\u95f2\u7f6e'), ('in', '\u62a5\u5e9f')], default='on', max_length=64, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('trade_date', models.CharField(blank=True, default='2016-01-01', max_length=64, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_date', models.CharField(blank=True, default='2016-01-01', max_length=64, verbose_name='\u4fdd\u4fee\u671f')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='\u4ef7\u683c(\u5143)')),
                ('price_total', models.IntegerField(blank=True, help_text='\u5982\u679c\u662f\u79df\u7684vps\uff0c\u8ba1\u7b97\u6bcf\u6708\u7eed\u4fdd\u53ef\u4ee5\u7b97\u51fa\u6210\u672c', null=True, verbose_name='\u7eed\u4fdd\u6b21\u6570')),
                ('applicant', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8d44\u4ea7\u7533\u8bf7\u8005')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('mark', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d44\u4ea7\u7ba1\u7406\u5458')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7Asset',
                'verbose_name_plural': '\u8d44\u4ea7Asset',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u673a\u67dc\u540d\u79f0')),
                ('brander', models.CharField(max_length=64, verbose_name='\u673a\u67dc\u54c1\u724c')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u673a\u623fcabinet',
                'verbose_name_plural': '\u673a\u623fcabinet',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_model', models.CharField(blank=True, max_length=128, verbose_name='CPU\u578b\u53f7')),
                ('cpu_count', models.SmallIntegerField(blank=True, default='2', verbose_name='\u7269\u7406cpu\u4e2a\u6570')),
                ('cpu_core_count', models.SmallIntegerField(blank=True, default='2', verbose_name='cpu\u6838\u6570')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668CPU',
                'verbose_name_plural': '\u670d\u52a1\u5668CPU',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('slot', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u63d2\u69fd\u4f4d')),
                ('manufactory', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.FloatField(verbose_name='\u78c1\u76d8\u5bb9\u91cfGB')),
                ('iface_type', models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD')], default='SAS', max_length=64, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668DISK',
                'verbose_name_plural': '\u670d\u52a1\u5668DISK',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('contacts', models.CharField(max_length=64, verbose_name='\u673a\u623f\u8d1f\u8d23\u4eba')),
                ('idc_phone', models.IntegerField(verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('contacts_phone', models.IntegerField(verbose_name='\u8d1f\u8d23\u4eba\u7535\u8bdd')),
                ('idc_addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('bandwidth', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u673a\u623f\u5e26\u5bbd')),
                ('operator', models.CharField(blank=True, help_text='\u4f8b\u5982\uff1a\u7535\u4fe1 \u8054\u901a \u6559\u80b2\u7f51 \u957f\u57ce\u5bbd\u5e26\u7b49,\u56fd\u5916\u8fd0\u884c\u5546\u4e0d\u4e00\u6837', max_length=32, null=True, verbose_name='\u673a\u623f\u8fd0\u8425\u5546')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': 'IDC\u673a\u623f',
                'verbose_name_plural': 'IDC\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='\u4ea7\u54c1\u7ebf')),
                ('slug', models.TextField(blank=True, max_length=128, null=True, verbose_name='\u7b80\u4ecb')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u7ebf',
                'verbose_name_plural': '\u4ea7\u54c1\u7ebf',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u5382\u5546\u6216\u4f9b\u5e94\u5546\u540d\u79f0')),
                ('support_num', models.CharField(blank=True, max_length=30, verbose_name='\u652f\u6301\u7535\u8bdd')),
                ('support_email', models.EmailField(blank=True, max_length=68, verbose_name='\u5382\u5546\u90ae\u4ef6')),
                ('memo', models.CharField(blank=True, max_length=128, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u5382\u5546\u6216\u4f9b\u5e94\u5546',
                'verbose_name_plural': '\u8bbe\u5907\u5382\u5546\u6216\u4f9b\u5e94\u5546',
            },
        ),
        migrations.CreateModel(
            name='Moudle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u673a\u623f\u6a21\u5757')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='\u5c5e\u4e8e')),
            ],
            options={
                'verbose_name': '\u673a\u623farea',
                'verbose_name_plural': '\u673a\u623farea',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5361\u540d')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7f51\u5361\u578b\u53f7')),
                ('macaddress', models.CharField(blank=True, max_length=64, verbose_name='MAC')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('netmask', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('bonding', models.CharField(blank=True, max_length=64, null=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('mark', models.BooleanField(default='False')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668NIC',
                'verbose_name_plural': '\u670d\u52a1\u5668NIC',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u9879\u76ee\u540d')),
                ('aliases_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u522b\u540d\uff0c\u7528\u4e8e\u76d1\u63a7')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u9879\u76ee\u4ecb\u7ecd')),
                ('project_doc', models.TextField(blank=True, null=True, verbose_name='\u9879\u76ee\u7ef4\u62a4\u8bf4\u660e')),
                ('project_user_group', models.TextField(blank=True, help_text='\u53ea\u6709\u9879\u76ee\u7ec4\u6210\u5458\u624d\u80fd\u7533\u8bf7\u53d1\u5e03', null=True, verbose_name='\u7ec4\u6210\u5458')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6392\u5e8f')),
                ('line', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='assets.Line', verbose_name='\u4ea7\u54c1\u7ebf')),
                ('project_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_business', to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='RaidAdaptor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('slot', models.CharField(blank=True, max_length=64, verbose_name='\u63d2\u53e3')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u578b\u53f7')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668Raid\u5361',
                'verbose_name_plural': '\u670d\u52a1\u5668Raid\u5361',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('slot', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u63d2\u69fd')),
                ('capacity', models.IntegerField(verbose_name='\u5185\u5b58\u5927\u5c0f(GB)')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668RAM',
                'verbose_name_plural': '\u670d\u52a1\u5668RAM',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u4e3b\u673a\u540d')),
                ('ssh_host', models.GenericIPAddressField(blank=True, help_text='\u4e00\u822c\u586b\u5199\u5916\u7f51IP', null=True, verbose_name='SSH\u5730\u5740')),
                ('ssh_port', models.SmallIntegerField(blank=True, default='22', null=True, verbose_name='SSH\u7aef\u53e3')),
                ('ssh_password', models.CharField(blank=True, max_length=100, verbose_name='SSH\u5bc6\u94a5')),
                ('ipmitool', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u8fdc\u63a7IP')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u54c1\u724c\u578b\u53f7')),
                ('server_sn', models.CharField(blank=True, max_length=32, null=True, verbose_name='SN\u7f16\u53f7')),
                ('Services_Code', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u5feb\u901f\u670d\u52a1\u7f16\u7801')),
                ('system_status', models.IntegerField(blank=True, choices=[(0, '\u672a\u5b89\u88c5\u7cfb\u7edf'), (1, '\u5df2\u5b89\u88c5\u7cfb\u7edf')], null=True, verbose_name='\u7cfb\u7edf\u72b6\u6001')),
                ('os_type', models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('unix', 'unix')], max_length=32, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('os_version', models.CharField(blank=True, choices=[('CentOS', 'CentOS'), ('Ubuntu', 'Ubuntu'), ('Windows Server', 'Windows Server')], max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('os_release', models.CharField(blank=True, choices=[('5', '5'), ('6', '6'), ('7', '7'), ('12.04', '12.04'), ('14.04', '14.04'), ('16.04', '16.04'), ('2003', '2003'), ('2008', '2008'), ('2012', '2012'), ('2016', '2016')], max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c\u53f7')),
                ('os_kernel', models.CharField(blank=True, choices=[('2.6.32', '2.6.32'), ('3.2.82', '3.2.82'), ('3.4.112', '3.4.112'), ('3.10.103', '3.10.103'), ('3.12.64', '3.12.64'), ('3.16.37', '3.16.37'), ('3.18.43', '3.18.43'), ('4.1.34', '4.1.34'), ('4.4.25', '4.4.25'), ('4.7.8', '4.7.8'), ('4.8.2', '4.8.2')], max_length=128, null=True, verbose_name='\u7cfb\u7edf\u5185\u6838')),
                ('Raid_level', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u5197\u4f59\u7ea7\u522b')),
                ('Disk_total', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u786c\u76d8\u603b\u5bb9\u91cf(GB)')),
                ('RAM_total', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u5185\u5b58\u603b\u5bb9\u91cf(GB)')),
                ('server_cabinet_id', models.IntegerField(blank=True, null=True, verbose_name='\u673a\u5668\u4f4d\u7f6e')),
                ('env', models.CharField(blank=True, choices=[('aliyun', 'aliyun'), ('aws', 'aws'), ('Tencent', 'Tencent'), ('pub', 'pub')], max_length=32, null=True, verbose_name='\u7cfb\u7edf\u73af\u5883')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Cabinet', verbose_name='\u6240\u5c5e\u673a\u67dc')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.IDC', verbose_name='\u673a\u623f')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_server', to='assets.Server', verbose_name='\u865a\u62df\u673a\u7236\u4e3b\u673a')),
                ('project', models.ManyToManyField(blank=True, to='assets.Project', verbose_name='\u6240\u5c5e\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7Server',
                'verbose_name_plural': '\u8d44\u4ea7Server',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='\u7528\u4e8e\u670d\u52a1\u7684\u5f00\u542f\u505c\u6b62\u6216\u91cd\u8f7d\uff0c\u5982: "service nginxd restart"', max_length=30, unique=True, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8fd0\u884c\u670d\u52a1',
                'verbose_name_plural': '\u8fd0\u884c\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u6807\u7b7e\u540d')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7Tag',
                'verbose_name_plural': '\u8d44\u4ea7Tag',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='service',
            field=models.ManyToManyField(blank=True, to='assets.Service', verbose_name='\u8fd0\u884c\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAN', to='assets.Moudle', verbose_name='\u6240\u5c5e\u6a21\u5757'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufactory', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assets.Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('asset', 'slot')]),
        ),
    ]
