# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('asset_type', models.CharField(choices=[('server', '\u7269\u7406\u673a'), ('server', '\u865a\u62df\u673a'), ('switch', '\u4ea4\u6362\u673a'), ('router', '\u8def\u7531\u5668'), ('firewall', '\u9632\u706b\u5899'), ('storage', '\u5b58\u50a8\u8bbe\u5907'), ('contain', 'Docker'), ('others', '\u5176\u5b83\u7c7b')], default='server', max_length=64, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sn', models.CharField(max_length=128, verbose_name='\u8d44\u4ea7SN\u53f7')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP')),
                ('management_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7ba1\u7406\u5730\u5740\u6216api')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u4fee\u671f')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='\u4ef7\u683c')),
                ('status', models.CharField(choices=[('on', '\u7ebf\u4e0a\u4f7f\u7528'), ('wait', '\u7ebf\u4e0b\u95f2\u7f6e'), ('in', '\u62a5\u5e9f'), ('lose', '\u672a\u77e5\u72b6\u6001')], default='on', max_length=64, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d44\u4ea7\u7ba1\u7406\u5458')),
            ],
            options={
                'verbose_name': '\u8d44\u4ea7\u603b\u8868',
                'verbose_name_plural': '\u8d44\u4ea7\u603b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='\u673a\u67dc\u540d\u79f0')),
                ('quantity', models.CharField(max_length=64, verbose_name='\u7535\u91cf')),
                ('first_port', models.IntegerField(verbose_name='\u4e0a\u8054\u7aef\u53e3')),
                ('bandwidth', models.CharField(max_length=64, verbose_name='\u5e26\u5bbd')),
                ('put_position', models.CharField(choices=[('forward', '\u6b63\u5411\u6446\u653e'), ('reverse', '\u53cd\u5411\u6446\u653e')], default='reverse', max_length=64, verbose_name='\u6446\u653e\u89c4\u5219')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u673a\u67dc',
                'verbose_name_plural': '\u673a\u67dc',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('cpu_model', models.CharField(blank=True, max_length=128, verbose_name='CPU\u578b\u53f7')),
                ('cpu_count', models.SmallIntegerField(verbose_name='\u7269\u7406cpu\u4e2a\u6570')),
                ('cpu_core_count', models.SmallIntegerField(verbose_name='cpu\u6838\u6570')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': 'CPU\u90e8\u4ef6',
                'verbose_name_plural': 'CPU\u90e8\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('slot', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u63d2\u69fd\u4f4d')),
                ('manufactory', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.FloatField(verbose_name='\u78c1\u76d8\u5bb9\u91cfGB')),
                ('iface_type', models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD')], default='SAS', max_length=64, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u786c\u76d8',
                'verbose_name_plural': '\u786c\u76d8',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('contacts', models.CharField(max_length=63, verbose_name='\u673a\u623f\u8d1f\u8d23\u4eba')),
                ('idc_phone', models.IntegerField(verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('contacts_phone', models.IntegerField(verbose_name='\u8d1f\u8d23\u4eba\u7535\u8bdd')),
                ('idc_addr', models.CharField(max_length=63, verbose_name='\u673a\u623f\u5730\u5740')),
                ('bandwidth', models.CharField(max_length=63, verbose_name='\u673a\u623f\u5e26\u5bbd')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': 'IDC\u673a\u623f',
                'verbose_name_plural': 'IDC\u673a\u623f',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='\u4ea7\u54c1\u7ebf')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u522b\u540d')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u7ebf',
                'verbose_name_plural': '\u4ea7\u54c1\u7ebf',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('manufactory', models.CharField(max_length=64, unique=True, verbose_name='\u5382\u5546\u6216\u4f9b\u5e94\u5546\u540d\u79f0')),
                ('support_num', models.CharField(blank=True, max_length=30, verbose_name='\u652f\u6301\u7535\u8bdd')),
                ('memo', models.CharField(blank=True, max_length=128, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u5382\u5546\u6216\u4f9b\u5e94\u5546',
                'verbose_name_plural': '\u8bbe\u5907\u5382\u5546\u6216\u4f9b\u5e94\u5546',
            },
        ),
        migrations.CreateModel(
            name='Moudle',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u673a\u623f\u6a21\u5757')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='\u5c5e\u4e8e')),
            ],
            options={
                'verbose_name': '\u673a\u623f\u6a21\u5757',
                'verbose_name_plural': '\u673a\u623f\u6a21\u5757',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('vlan_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='VlanIP')),
                ('intranet_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5185\u7f51IP')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('port_num', models.SmallIntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u4e2a\u6570')),
                ('device_detail', models.TextField(blank=True, null=True, verbose_name='\u8bbe\u7f6e\u8be6\u7ec6\u914d\u7f6e')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u8bbe\u5907',
                'verbose_name_plural': '\u7f51\u7edc\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5361\u540d')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7f51\u5361\u578b\u53f7')),
                ('macaddress', models.CharField(max_length=64, unique=True, verbose_name='MAC')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('netmask', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('bonding', models.CharField(blank=True, max_length=64, null=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u7f51\u5361',
                'verbose_name_plural': '\u7f51\u5361',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u8fd0\u8425\u5546')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8fd0\u8425\u5546',
                'verbose_name_plural': '\u8fd0\u8425\u5546',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('service_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u9879\u76ee\u540d')),
                ('aliases_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u522b\u540d\uff0c\u7528\u4e8e\u76d1\u63a7')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u8bf4\u660e')),
                ('project_doc', models.TextField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u7ef4\u62a4\u8bf4\u660e')),
                ('project_user_group', models.TextField(blank=True, help_text='\u53ea\u6709\u9879\u76ee\u7ec4\u6210\u5458\u624d\u80fd\u7533\u8bf7\u53d1\u5e03', null=True, verbose_name='\u7ec4\u6210\u5458')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='\u6392\u5e8f')),
                ('line', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='assets.Line', verbose_name='\u4ea7\u54c1\u7ebf')),
                ('project_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_business', to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1',
                'verbose_name_plural': '\u4e1a\u52a1',
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('env', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9879\u76ee\u73af\u5883')),
                ('project', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='assets.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u7ba1\u7406\u4eba\u5458',
                'verbose_name_plural': '\u4e1a\u52a1\u7ba1\u7406\u4eba\u5458',
            },
        ),
        migrations.CreateModel(
            name='RaidAdaptor',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u53e3')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u578b\u53f7')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': 'raid\u5361',
                'verbose_name_plural': 'raid\u5361',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(max_length=128, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd')),
                ('capacity', models.IntegerField(verbose_name='\u5185\u5b58\u5927\u5c0f(MB)')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '\u5185\u5b58',
                'verbose_name_plural': '\u5185\u5b58',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=32)),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u578b\u53f7')),
                ('kernelrelease', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u6838')),
                ('raid_type', models.CharField(blank=True, max_length=512, null=True, verbose_name='raid\u7ea7\u522b')),
                ('server_status', models.IntegerField(blank=True, choices=[(0, '\u672a\u5b89\u88c5\u7cfb\u7edf'), (1, '\u5df2\u5b89\u88c5\u7cfb\u7edf')], default=0, verbose_name='\u673a\u5668\u72b6\u6001')),
                ('os_type', models.CharField(blank=True, choices=[(0, 'Linux'), (1, 'windows')], default=0, max_length=32, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('os_distribution', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('os_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c\u53f7')),
                ('env', models.CharField(blank=True, choices=[('aliy', 'aliy'), ('aws', 'aws'), ('prod', 'prod'), ('pub', 'pub')], max_length=32, null=True, verbose_name='\u8fd0\u884c\u73af\u5883')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('hosted_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_on_server', to='assets.Server', verbose_name='\u865a\u62df\u673a\u7236\u4e3b\u673a')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668',
                'verbose_name_plural': '\u670d\u52a1\u5668',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='\u6ce8\u610f\uff0c\u6240\u6709\u670d\u52a1\u64cd\u4f5c\u5168\u90e8\u671f\u4e8elinux\u670d\u52a1\u64cd\u4f5c\uff0c\u5982: "service iptables restart"', max_length=30, unique=True, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8fd0\u884c\u670d\u52a1',
                'verbose_name_plural': '\u8fd0\u884c\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Tag name')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='service',
            field=models.ManyToManyField(blank=True, to='assets.Service', verbose_name='\u8fd0\u884c\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='idc',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Operator', verbose_name='\u8fd0\u8425\u5546'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Moudle', verbose_name='\u6240\u5c5e\u6a21\u5757'),
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Cabinet', verbose_name='\u6240\u5c5e\u673a\u67dc'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufactory', verbose_name='\u4f9b\u5e94\u5546'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assets.Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='ram',
            unique_together=set([('asset', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='raidadaptor',
            unique_together=set([('asset', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([('asset', 'slot')]),
        ),
    ]
