# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manufactory',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price_total',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='trade_date',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='bonding',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='macaddress',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='model',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='netmask',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aliases_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='line',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_doc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_user_group',
        ),
        migrations.RemoveField(
            model_name='server',
            name='Raid_level',
        ),
        migrations.RemoveField(
            model_name='server',
            name='Services_Code',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ansible_name',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='server',
            name='env',
        ),
        migrations.RemoveField(
            model_name='server',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ipmitool',
        ),
        migrations.RemoveField(
            model_name='server',
            name='model',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_kernel',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_release',
        ),
        migrations.RemoveField(
            model_name='server',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_cabinet_id',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_sn',
        ),
        migrations.RemoveField(
            model_name='server',
            name='system_status',
        ),
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mychilden', to='assets.Project', verbose_name='\u7236\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='\u9879\u76ee\u540d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='\u5c42\u7ea7'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project_servers', to='assets.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
