# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-02 13:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('mobile', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid mobile number.', 'invalid')], verbose_name='\u624b\u673a')),
                ('session_key', models.CharField(blank=True, max_length=60, null=True, verbose_name='session_key')),
                ('user_key', models.TextField(blank=True, null=True, verbose_name='\u7528\u6237\u767b\u5f55key')),
                ('menu_status', models.BooleanField(default=False, verbose_name='\u7528\u6237\u83dc\u5355\u72b6\u6001')),
                ('user_active', models.BooleanField(default=0, verbose_name='\u8bbe\u7f6e\u5bc6\u7801\u72b6\u6001')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='department_Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('desc_gid', models.IntegerField(blank=True, choices=[(1001, '\u8fd0\u7ef4\u90e8'), (1002, '\u67b6\u6784'), (1003, '\u7814\u53d1dev'), (1004, '\u6d4b\u8bd5')], null=True, verbose_name='\u90e8\u95e8\u7ec4')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_groups_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7ec4\u540d')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8\u7ec4',
                'verbose_name_plural': '\u90e8\u95e8\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='server_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u670d\u52a1\u5668')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7528\u6237\u540d')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u59d3\u540d')),
                ('auth_weights', models.BooleanField(default=0, verbose_name='\u6743\u9650')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u65e5\u5fd7\u8bb0\u5f55',
                'verbose_name_plural': '\u65e5\u5fd7\u8bb0\u5f55',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.department_Mode', verbose_name='\u90e8\u95e8'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
