# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-22 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_auth_cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_a_group', models.BooleanField(default=False, verbose_name='\u67e5\u770b\u8d44\u4ea7\u7ec4')),
                ('add_a_group', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u8d44\u4ea7\u7ec4')),
                ('edit_a_group', models.BooleanField(default=False, verbose_name='\u66f4\u65b0\u8d44\u4ea7\u7ec4')),
                ('delete_a_group', models.BooleanField(default=False, verbose_name='\u5220\u9664\u8d44\u4ea7\u7ec4')),
                ('select_host', models.BooleanField(default=False, verbose_name='\u67e5\u770b\u8d44\u4ea7')),
                ('update_host', models.BooleanField(default=False, verbose_name='\u66f4\u65b0\u8d44\u4ea7')),
                ('add_host', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u8d44\u4ea7')),
                ('delete_host', models.BooleanField(default=False, verbose_name='\u5220\u9664\u8d44\u4ea7')),
                ('show_pro', models.BooleanField(default=False, verbose_name='\u67e5\u770b\u9879\u76ee')),
                ('add_pro', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u9879\u76ee')),
                ('money_fabu', models.BooleanField(default=False, verbose_name='\u73b0\u91d1\u7f51\u53d1\u5e03')),
                ('money_gengxin', models.BooleanField(default=False, verbose_name='\u73b0\u91d1\u7f51\u66f4\u65b0')),
                ('manniu_fabu', models.BooleanField(default=False, verbose_name='\u86ee\u725b\u53d1\u5e03')),
                ('manniu_gengxin', models.BooleanField(default=False, verbose_name='\u86ee\u725b\u66f4\u65b0')),
                ('auth_project', models.BooleanField(default=False, verbose_name='\u5c55\u793a\u6211\u7684\u4efb\u52a1')),
                ('auditor_manage', models.BooleanField(default=False, verbose_name='\u5ba1\u6838\u4eba\u7ba1\u7406')),
                ('one_key', models.BooleanField(default=False, verbose_name='\u4e00\u952e\u901a\u8fc7\u6743\u9650')),
                ('add_user', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u7528\u6237')),
                ('edit_user', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u7528\u6237')),
                ('edit_pass', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u5bc6\u7801')),
                ('delete_user', models.BooleanField(default=False, verbose_name='\u5220\u9664\u7528\u6237')),
                ('show_department', models.BooleanField(default=False, verbose_name='\u67e5\u770b\u7ec4')),
                ('add_department', models.BooleanField(default=False, verbose_name='\u6dfb\u52a0\u7ec4')),
                ('edit_department', models.BooleanField(default=False, verbose_name='\u4fee\u6539\u7ec4')),
                ('delete_department', models.BooleanField(default=False, verbose_name='\u5220\u9664\u7ec4')),
                ('show_white', models.BooleanField(default=False, verbose_name='\u767d\u540d\u5355\u67e5\u770b')),
                ('edit_white', models.BooleanField(default=False, verbose_name='\u767d\u540d\u5355\u589e\u5220\u6539')),
                ('show_domain', models.BooleanField(default=False, verbose_name='\u57df\u540d\u67e5\u770b')),
                ('edit_domain', models.BooleanField(default=False, verbose_name='\u57df\u540d\u4fee\u6539')),
                ('add_domain', models.BooleanField(default=False, verbose_name='\u57df\u540d\u589e\u52a0')),
                ('delete_domain', models.BooleanField(default=False, verbose_name='\u57df\u540d\u5220\u9664')),
                ('show_nginx', models.BooleanField(default=False, verbose_name='\u5907\u7528\u540e\u53f0\u67e5\u770b')),
                ('edit_nginx', models.BooleanField(default=False, verbose_name='\u5907\u7528\u540e\u53f0\u4fee\u6539')),
                ('add_nginx', models.BooleanField(default=False, verbose_name='\u5907\u7528\u540e\u53f0\u589e\u52a0')),
                ('delete_nginx', models.BooleanField(default=False, verbose_name='\u5907\u7528\u540e\u53f0\u5220\u9664')),
                ('show_dns', models.BooleanField(default=False, verbose_name='\u67e5\u770bdns')),
                ('show_wiki', models.BooleanField(default=False, verbose_name='\u67e5\u770bwiki')),
                ('add_wiki', models.BooleanField(default=False, verbose_name='wiki\u64cd\u4f5c')),
                ('test_fun', models.BooleanField(default=False, verbose_name='\u663e\u793a\u672a\u4e0a\u7ebf\u6d4b\u8bd5\u9879\u76ee')),
            ],
            options={
                'verbose_name': '\u7ec4\u6743\u9650',
                'verbose_name_plural': '\u7ec4\u6743\u9650',
            },
        ),
        migrations.AlterModelOptions(
            name='department_mode',
            options={'verbose_name': '\u6210\u5458\u7ec4', 'verbose_name_plural': '\u6210\u5458\u7ec4'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department_mode',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='department_mode',
            name='desc_gid',
        ),
        migrations.RemoveField(
            model_name='department_mode',
            name='description',
        ),
        migrations.AddField(
            model_name='department_mode',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_manager', to=settings.AUTH_USER_MODEL, verbose_name='\u7ec4\u957f'),
        ),
        migrations.AddField(
            model_name='department_mode',
            name='members',
            field=models.ManyToManyField(related_name='group_users', to=settings.AUTH_USER_MODEL, verbose_name='\u6240\u5c5e\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='department_mode',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u7ec4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=60, verbose_name='Telegram_Bot_Chat_ID'),
        ),
        migrations.AddField(
            model_name='department_auth_cmdb',
            name='department_name',
            field=models.ForeignKey(help_text='\u6dfb\u52a0\u7ec4\u6743\u9650', on_delete=django.db.models.deletion.CASCADE, related_name='group_auth', to='accounts.department_Mode', verbose_name='\u6240\u5c5e\u7ec4'),
        ),
    ]
