# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-17 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180122_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_auth_cmdb',
            name='observer',
            field=models.BooleanField(default=False, verbose_name='\u4efb\u52a1\u72b6\u6001\u89c2\u5bdf\u8005'),
        ),
        migrations.AlterField(
            model_name='department_mode',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_manager', to=settings.AUTH_USER_MODEL, verbose_name='\u7ec4\u957f'),
        ),
    ]
