# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-02 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
        ('Allow_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldsite_line',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iptables',
            name='i_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Platform', verbose_name='\u6240\u5c5e\u5e73\u53f0'),
        ),
        migrations.AddField(
            model_name='iptables',
            name='i_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
