# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-23 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Allow_list', '0002_auto_20180122_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptables',
            name='i_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='iptables',
            name='i_comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
