# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-26 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allow_list', '0002_iptables_i_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptables',
            name='i_comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
