# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-07-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allow_list', '0004_auto_20180203_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='white_conf',
            name='exception_ip',
            field=models.TextField(blank=True, null=True, verbose_name='\u4f8b\u5916IP'),
        ),
        migrations.AlterField(
            model_name='white_conf',
            name='name',
            field=models.CharField(choices=[('DT-GFC', '\u9f0e\u6cf0\u5b98\u65b9\u5f69\u767d\u540d\u5355'), ('MN-GFC', '\u86ee\u725b\u5b98\u65b9\u5f69\u767d\u540d\u5355'), ('MN-JDC', '\u86ee\u725b\u7ecf\u5178\u5f69\u767d\u540d\u5355'), ('KG-JDC', 'KG\u7ecf\u5178\u5f69\u767d\u540d\u5355'), ('MN-Backend', '\u86ee\u725b\u540e\u53f0\u767d\u540d\u5355'), ('MONEY-Backend', '\u73b0\u91d1\u7f51\u540e\u53f0\u767d\u540d\u5355'), ('MONEY-Black', '\u73b0\u91d1\u7f51\u540e\u53f0\u9ed1\u540d\u5355'), ('MN-Black', '\u86ee\u725b\u540e\u53f0\u9ed1\u540d\u5355')], max_length=25, unique=True, verbose_name='\u767d\u540d\u5355\u914d\u7f6e'),
        ),
    ]
