# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-12-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allow_list', '0005_auto_20180716_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='white_list',
            name='memo',
            field=models.TextField(default='', verbose_name='\u5907\u6ce8'),
        ),
    ]
