# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Allow_list', '0006_white_list_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='dsACL_ngx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
                ('delTask', models.BooleanField(default=False, verbose_name='\u5b9a\u65f6\u5220\u9664\u4efb\u52a1')),
                ('delDateTime', models.DateTimeField(blank=True, null=True, verbose_name='\u5b9a\u65f6\u5220\u9664\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dsACL_SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('useParentConf', models.BooleanField(default=True)),
                ('servers', models.TextField(blank=True, verbose_name='\u670d\u52a1\u5668\u5730\u5740')),
                ('filename', models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u7edd\u5bf9\u8def\u5f84')),
                ('rule', models.TextField(verbose_name='\u5339\u914d\u89c4\u5219')),
                ('hook', models.TextField(blank=True, verbose_name='\u94a9\u5b50')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dsACL_TopProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('servers', models.TextField(blank=True, verbose_name='\u670d\u52a1\u5668\u5730\u5740')),
                ('filename', models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u7edd\u5bf9\u8def\u5f84')),
                ('rule', models.TextField(verbose_name='\u5339\u914d\u89c4\u5219')),
                ('limit', models.IntegerField(verbose_name='\u76f8\u540cIP\u9650\u5236\u6761\u76ee')),
                ('exception', models.TextField(blank=True, verbose_name='\u65e0\u9650\u5236IP')),
                ('hook', models.TextField(blank=True, verbose_name='\u94a9\u5b50')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='expiration_reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(choices=[('domain', '\u57df\u540d'), ('certificate', '\u8bc1\u4e66'), ('server', '\u670d\u52a1\u5668')], max_length=12, verbose_name='\u7c7b\u578b')),
                ('text', models.TextField(verbose_name='\u5185\u5bb9')),
                ('is_alert', models.BooleanField(default=False, verbose_name='\u662f\u5426\u62a5\u8b66')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='\u662f\u5426\u786e\u8ba4')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(verbose_name='\u8fc7\u671f\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='pre_Add_acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('project', models.CharField(max_length=64, verbose_name='\u9879\u76eeID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='pre_Add_remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.GenericIPAddressField()),
                ('filename', models.CharField(max_length=100, verbose_name='\u6587\u4ef6\u7edd\u5bf9\u8def\u5f84')),
                ('count', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_logs', to='Allow_list.pre_Add_acl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='white_conf',
            name='hook',
            field=models.TextField(blank=True, null=True, verbose_name='\u94a9\u5b50'),
        ),
        migrations.AlterField(
            model_name='iptables',
            name='i_ports',
            field=models.CharField(blank=True, default='80,443', max_length=30),
        ),
        migrations.AlterField(
            model_name='iptables',
            name='i_position',
            field=models.CharField(blank=True, default=3, max_length=30),
        ),
        migrations.AlterField(
            model_name='white_conf',
            name='name',
            field=models.CharField(choices=[('DT-GFC', '\u9f0e\u6cf0\u5b98\u65b9\u5f69\u767d\u540d\u5355'), ('MN-GFC', '\u86ee\u725b\u5b98\u65b9\u5f69\u767d\u540d\u5355'), ('MN-JDC', '\u86ee\u725b\u7ecf\u5178\u5f69\u767d\u540d\u5355'), ('KG-JDC', 'KG\u7ecf\u5178\u5f69\u767d\u540d\u5355'), ('MN-Backend', '\u86ee\u725b\u540e\u53f0\u767d\u540d\u5355'), ('MONEY-Backend', '\u73b0\u91d1\u7f51\u540e\u53f0\u767d\u540d\u5355'), ('MONEY-Black', '\u73b0\u91d1\u7f51\u524d\u7aef\u9ed1\u540d\u5355'), ('MN-Black', '\u86ee\u725b\u524d\u7aef\u9ed1\u540d\u5355'), ('api-bin', '\u5916\u63a5bbin\u767d\u540d\u5355'), ('api-jdc', '\u5916\u63a5\u7ecf\u5178\u624d\u767d\u540d\u5355'), ('api-gfc', '\u5916\u63a5\u5b98\u65b9\u5f69\u767d\u540d\u5355')], max_length=25, unique=True, verbose_name='\u767d\u540d\u5355\u914d\u7f6e'),
        ),
        migrations.AddField(
            model_name='dsacl_subproject',
            name='parentPro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Allow_list.dsACL_TopProject'),
        ),
        migrations.AddField(
            model_name='dsacl_ngx',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Allow_list.dsACL_SubProject'),
        ),
        migrations.AddField(
            model_name='dsacl_ngx',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
