# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allow_list', '0007_auto_20190701_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsacl_ngx',
            name='zone',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='dsacl_topproject',
            name='globalip',
            field=models.TextField(blank=True, verbose_name='\u9ed8\u8ba4\u6dfb\u52a0IP'),
        ),
    ]
