# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Allow_list', '0008_auto_20190705_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsacl_subproject',
            name='name',
            field=models.CharField(max_length=64, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
