# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-26 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ops_command_log',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=64, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.CharField(max_length=64, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('command', models.TextField(verbose_name='\u5185\u5bb9')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u8fd0\u7ef4\u5ba1\u8ba1\u65e5\u5fd7',
                'verbose_name_plural': '\u8fd0\u7ef4\u5ba1\u8ba1\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='task_audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.TextField(verbose_name='\u5185\u5bb9')),
                ('isaudit', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('ispass', models.BooleanField(default=False, verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('audit_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5ba1\u6838\u65f6\u95f4')),
                ('postil', models.TextField(blank=True, null=True, verbose_name='\u6279\u6ce8')),
                ('loss_efficacy', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8fc7\u671f')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audi', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6838\u4eba')),
                ('gengxin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.gengxin_deploy')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u8d77\u4eba')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u5ba1\u6838',
                'verbose_name_plural': '\u4efb\u52a1\u5ba1\u6838',
            },
        ),
    ]
