# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-15 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180716_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_audit',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='task_audit',
            name='gengxin',
        ),
        migrations.RemoveField(
            model_name='task_audit',
            name='initiator',
        ),
        migrations.DeleteModel(
            name='task_audit',
        ),
    ]
