# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-26 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bug_type', models.CharField(choices=[('code_bug', '\u4ee3\u7801bug'), ('intenet_bug', '\u7f51\u7edc\u6545\u969c'), ('server_bug', '\u670d\u52a1\u5668\u6545\u969c'), ('service_bug', '\u5e94\u7528\u670d\u52a1\u6545\u969c'), ('preson_bug', '\u8bef\u64cd\u4f5c\u6545\u969c'), ('attack_bug', '\u88ab\u653b\u51fb'), ('other_bug', '\u5176\u4ed6')], max_length=64, verbose_name='\u6545\u969c\u7c7b\u578b')),
                ('bug_name', models.CharField(max_length=64, verbose_name='\u6545\u969c\u540d\u79f0')),
                ('bug_status', models.CharField(choices=[('0', '\u53d1\u73b0\u4e0a\u62a5'), ('1', '\u5904\u7406\u4e2d'), ('2', '\u5df2\u89e3\u51b3')], max_length=100, verbose_name='\u6545\u969c\u72b6\u6001')),
                ('bug_level', models.CharField(choices=[('0', '\u4e00\u822c\u6545\u969c'), ('1', '\u91cd\u8981\u6545\u969c'), ('2', '\u4e25\u91cd\u6545\u969c'), ('3', '\u707e\u96be\u6545\u969c')], max_length=100, verbose_name='\u6545\u969c\u7ea7\u522b')),
                ('bug_level_change', models.BooleanField(default=False, verbose_name='\u6545\u969c\u662f\u5426\u5347\u7ea7')),
                ('appear_time', models.IntegerField(blank=True, null=True, verbose_name='\u51fa\u73b0\u6b21\u6570')),
                ('bug_accept', models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a5\u5355')),
                ('bug_assigned_change', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6c\u6d3e')),
                ('bug_solve', models.BooleanField(default=False, verbose_name='\u662f\u5426\u89e3\u51b3')),
                ('issue_description', models.TextField(blank=True, null=True, verbose_name='\u6545\u969c\u63cf\u8ff0')),
                ('resolution_step', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u6b65\u9aa4')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='\u8f6c\u6d3e\u539f\u56e0')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bug_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_assigned', to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba\u5458')),
                ('bug_change_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_change_assigned', to=settings.AUTH_USER_MODEL, verbose_name='\u8f6c\u6d3e\u4eba\u5458')),
                ('bug_tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_tracker', to=settings.AUTH_USER_MODEL, verbose_name='\u8ddf\u8e2a\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u6545\u969cBugs',
                'verbose_name_plural': '\u6545\u969cBugs',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=128, verbose_name='\u4e1a\u52a1\u5168\u540d')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='\u4e1a\u52a1\u7b80\u79f0')),
                ('nic_name', models.CharField(blank=True, max_length=64, verbose_name='\u53d1\u5e03\u4ee3\u53f7')),
                ('platform', models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('initsite_data', models.CharField(blank=True, max_length=64, verbose_name='\u5efa\u7ad9\u65f6\u95f4')),
                ('ip_info', models.TextField(blank=True, null=True, verbose_name='\u670d\u52a1\u5668\u4fe1\u606f')),
                ('status', models.CharField(blank=True, choices=[('0', '\u6b63\u5e38\u8fd0\u8f6c'), ('1', '\u7ef4\u62a4\u5347\u7ea7'), ('2', '\u8fc1\u79fb\u8fc7\u6e21'), ('3', '\u505c\u6b62\u8fd0\u8f6c')], max_length=100, verbose_name='\u4e1a\u52a1\u72b6\u6001')),
                ('status_update_date', models.CharField(blank=True, max_length=64, verbose_name='\u72b6\u6001\u53d8\u66f4\u65f6\u95f4')),
                ('front_station', models.TextField(blank=True, null=True, verbose_name='\u524d\u7aef\u6e90\u7ad9')),
                ('front_station_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aefweb\u8def\u5f84')),
                ('front_station_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aefweb\u6587\u4ef6')),
                ('front_proxy', models.TextField(blank=True, null=True, verbose_name='\u524d\u7aef\u4ee3\u7406')),
                ('front_proxy_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aef\u4ee3\u7406web\u8def\u5f84')),
                ('front_proxy_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aef\u4ee3\u7406web\u6587\u4ef6')),
                ('backend_station', models.TextField(blank=True, null=True, verbose_name='ds168\u540e\u53f0\u6e90\u7ad9')),
                ('backend_station_web_dir', models.CharField(blank=True, max_length=64, verbose_name='ds168\u540e\u53f0web\u8def\u5f84')),
                ('backend_station_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u540e\u53f0web\u6587\u4ef6')),
                ('backend_proxy', models.TextField(blank=True, null=True, verbose_name='ag\u540e\u53f0\u4ee3\u7406')),
                ('backend_proxy_web_dir', models.CharField(blank=True, max_length=64, verbose_name='ag\u540e\u53f0\u4ee3\u7406web\u8def\u5f84')),
                ('backend_proxy_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u540e\u53f0\u4ee3\u7406web\u6587\u4ef6')),
                ('third_party_node', models.TextField(blank=True, null=True, verbose_name='\u7b2c\u4e09\u65b9\u53cd\u4ee3\u8282\u70b9')),
                ('third_proxy_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u4e09\u65b9\u53cd\u4ee3web\u8def\u5f84')),
                ('third_proxy_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u4e09\u65b9\u53cd\u4ee3web\u6587\u4ef6')),
                ('reserve_a', models.CharField(blank=True, max_length=40)),
                ('reserve_b', models.BooleanField(default=False, verbose_name='\u662f\u5426\u542f\u7528\u5907\u7528\u540e\u53f0\u57df\u540d')),
                ('reserve_c', models.CharField(blank=True, max_length=8)),
                ('reserve_d', models.CharField(blank=True, max_length=8)),
                ('reserve_e', models.CharField(blank=True, max_length=8)),
                ('reserve_f', models.CharField(blank=True, max_length=8)),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nic_name'],
                'verbose_name': '\u4e1a\u52a1Business',
                'verbose_name_plural': '\u4e1a\u52a1Business',
            },
        ),
        migrations.CreateModel(
            name='dnsmanage_apikey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('platform_name', models.CharField(choices=[('PODCN', 'dnspod\u4e2d\u56fd'), ('PODCOM', 'dnspod\u56fd\u9645'), ('CLOUDXNS', 'CloudXNS\u5feb\u7f51')], max_length=32, verbose_name='DNS\u670d\u52a1\u5546')),
                ('platform_addr', models.CharField(max_length=32, verbose_name='DNS\u89e3\u6790\u7f51\u5740')),
                ('user', models.CharField(max_length=32, verbose_name='\u8d26\u53f7')),
                ('passwd', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('keyone', models.CharField(max_length=64, verbose_name='\u4e3b\u79d8\u94a5')),
                ('keytwo', models.CharField(max_length=64, verbose_name='\u526f\u79d8\u94a5')),
                ('status', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u8d26\u6237\u8868',
                'verbose_name_plural': '\u8d26\u6237\u8868',
            },
        ),
        migrations.CreateModel(
            name='dnsmanage_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u57df\u540d')),
                ('name_id', models.IntegerField(verbose_name='\u57df\u540dID')),
                ('status', models.CharField(max_length=12, verbose_name='\u72b6\u6001')),
                ('records', models.IntegerField(blank=True, null=True, verbose_name='\u8bb0\u5f55\u6570')),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.dnsmanage_apikey', verbose_name='\u8d26\u53f7')),
            ],
            options={
                'verbose_name': '\u57df\u540d\u8868',
                'verbose_name_plural': '\u57df\u540d\u8868',
            },
        ),
        migrations.CreateModel(
            name='dnsmanage_record',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(verbose_name='\u8bb0\u5f55ID')),
                ('host_id', models.IntegerField(blank=True, null=True, verbose_name='\u4e3b\u673aID')),
                ('subdomain', models.CharField(max_length=32, verbose_name='\u5b50\u57df\u540d')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('NS', 'NS')], max_length=64, verbose_name='\u89e3\u6790\u7c7b\u578b')),
                ('value', models.CharField(max_length=64, verbose_name='\u89e3\u6790\u5230')),
                ('standby', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u7528\u503c')),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SUBRECORD', to='business.dnsmanage_name', verbose_name='\u57df\u540d')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BUSGROUP', to='business.Business')),
            ],
            options={
                'verbose_name': '\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='Domain_ip_pool',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, choices=[('CDN\uff08\u6297\u653b\u51fb\uff09', 'CDN\uff08\u6297\u653b\u51fb\uff09'), ('\u65b0\u7ad9\u540e\u53f0\u53cd\u4ee3', '\u65b0\u7ad9\u540e\u53f0\u53cd\u4ee3'), ('\u65b0\u7ad9\u7b2c\u4e09\u65b9ag\u53cd\u4ee3', '\u65b0\u7ad9\u7b2c\u4e09\u65b9ag\u53cd\u4ee3')], max_length=32, null=True, verbose_name='\u7ec4\u540d')),
                ('attribute', models.TextField(blank=True, verbose_name='IP\u5217\u8868')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u57df\u540dIP\u6c60',
                'verbose_name_plural': '\u57df\u540dIP\u6c60',
            },
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u57df\u540d')),
                ('use', models.CharField(blank=True, choices=[('0', '\u524d\u7aef\u57df\u540d'), ('1', '\u4ee3\u7406\u540e\u53f0\u57df\u540d'), ('2', '\u540e\u53f0\u57df\u540d'), ('3', '\u5bfc\u822a\u57df\u540d'), ('4', '\u5176\u4ed6\u57df\u540d')], max_length=64, verbose_name='\u7528\u9014')),
                ('classify', models.CharField(blank=True, default='online', max_length=32, verbose_name='\u73af\u5883')),
                ('state', models.CharField(blank=True, choices=[('0', '\u5907\u7528'), ('1', '\u518d\u7528'), ('2', '\u5f03\u7528')], max_length=64, verbose_name='\u57df\u540d\u72b6\u6001')),
                ('monitor_status', models.BooleanField(default=False, verbose_name='\u662f\u5426\u76d1\u63a7')),
                ('supplier', models.CharField(blank=True, max_length=32, verbose_name='\u7ba1\u7406\u8005')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Domain_ip_pool', verbose_name='\u89e3\u6790\u5230')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain', to='business.Business')),
            ],
            options={
                'verbose_name': '\u57df\u540dDomainName',
                'verbose_name_plural': '\u57df\u540dDomainName',
            },
        ),
        migrations.AddField(
            model_name='bugs',
            name='business',
            field=models.ManyToManyField(blank=True, to='business.Business', verbose_name='\u6d89\u53ca\u4e1a\u52a1'),
        ),
    ]
