# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-02 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bug_type', models.CharField(choices=[('code_bug', '\u4ee3\u7801bug'), ('intenet_bug', '\u7f51\u7edc\u6545\u969c'), ('server_bug', '\u670d\u52a1\u5668\u6545\u969c'), ('service_bug', '\u5e94\u7528\u670d\u52a1\u6545\u969c'), ('preson_bug', '\u8bef\u64cd\u4f5c\u6545\u969c'), ('attack_bug', '\u88ab\u653b\u51fb'), ('other_bug', '\u5176\u4ed6')], max_length=64, verbose_name='\u6545\u969c\u7c7b\u578b')),
                ('bug_name', models.CharField(max_length=64, verbose_name='\u6545\u969c\u540d\u79f0')),
                ('bug_status', models.CharField(choices=[('0', '\u53d1\u73b0\u4e0a\u62a5'), ('1', '\u5904\u7406\u4e2d'), ('2', '\u5df2\u89e3\u51b3')], max_length=100, verbose_name='\u6545\u969c\u72b6\u6001')),
                ('bug_level', models.CharField(choices=[('0', '\u4e00\u822c\u6545\u969c'), ('1', '\u91cd\u8981\u6545\u969c'), ('2', '\u4e25\u91cd\u6545\u969c'), ('3', '\u707e\u96be\u6545\u969c')], max_length=100, verbose_name='\u6545\u969c\u7ea7\u522b')),
                ('bug_level_change', models.BooleanField(default=False, verbose_name='\u6545\u969c\u662f\u5426\u5347\u7ea7')),
                ('appear_time', models.IntegerField(blank=True, null=True, verbose_name='\u51fa\u73b0\u6b21\u6570')),
                ('bug_accept', models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a5\u5355')),
                ('bug_assigned_change', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6c\u6d3e')),
                ('bug_solve', models.BooleanField(default=False, verbose_name='\u662f\u5426\u89e3\u51b3')),
                ('issue_description', models.TextField(blank=True, null=True, verbose_name='\u6545\u969c\u63cf\u8ff0')),
                ('resolution_step', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u6b65\u9aa4')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='\u8f6c\u6d3e\u539f\u56e0')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bug_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_assigned', to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba\u5458')),
                ('bug_change_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_change_assigned', to=settings.AUTH_USER_MODEL, verbose_name='\u8f6c\u6d3e\u4eba\u5458')),
                ('bug_tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_tracker', to=settings.AUTH_USER_MODEL, verbose_name='\u8ddf\u8e2a\u4eba\u5458')),
            ],
            options={
                'verbose_name': '\u6545\u969cBugs',
                'verbose_name_plural': '\u6545\u969cBugs',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=128, verbose_name='\u4e1a\u52a1\u5168\u540d')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='\u4e1a\u52a1\u7b80\u79f0')),
                ('nic_name', models.CharField(blank=True, max_length=64, verbose_name='\u53d1\u5e03\u4ee3\u53f7')),
                ('initsite_data', models.CharField(blank=True, max_length=64, verbose_name='\u5efa\u7ad9\u65f6\u95f4')),
                ('agent_contact', models.CharField(blank=True, max_length=100, verbose_name='\u5ba2\u6237\u540d')),
                ('agent_contact_method', models.CharField(blank=True, max_length=100, verbose_name='\u5ba2\u6237\u7535\u8bdd')),
                ('other_contact_method', models.CharField(blank=True, max_length=100, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('status', models.CharField(blank=True, choices=[('0', '\u6b63\u5e38\u8fd0\u8f6c'), ('1', '\u7ef4\u62a4\u5347\u7ea7'), ('2', '\u8fc1\u79fb\u8fc7\u6e21'), ('3', '\u505c\u6b62\u8fd0\u8f6c')], max_length=100, verbose_name='\u4e1a\u52a1\u72b6\u6001')),
                ('status_update_date', models.CharField(blank=True, max_length=64, verbose_name='\u72b6\u6001\u53d8\u66f4\u65f6\u95f4')),
                ('front_station_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aefweb\u8def\u5f84')),
                ('front_station_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aefweb\u6587\u4ef6')),
                ('front_proxy_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aef\u4ee3\u7406web\u8def\u5f84')),
                ('front_proxy_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u524d\u7aef\u4ee3\u7406web\u6587\u4ef6')),
                ('backend_station_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u540e\u53f0web\u8def\u5f84')),
                ('backend_station_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u540e\u53f0web\u6587\u4ef6')),
                ('backend_proxy_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u540e\u53f0\u4ee3\u7406web\u8def\u5f84')),
                ('backend_proxy_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u540e\u53f0\u4ee3\u7406web\u6587\u4ef6')),
                ('third_proxy_web_dir', models.CharField(blank=True, max_length=64, verbose_name='\u4e09\u65b9\u53cd\u4ee3web\u8def\u5f84')),
                ('third_proxy_web_file', models.CharField(blank=True, max_length=64, verbose_name='\u4e09\u65b9\u53cd\u4ee3web\u6587\u4ef6')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u4ecb\u7ecd')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('ds_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ds_contact', to=settings.AUTH_USER_MODEL, verbose_name='\u6211\u53f8\u4e13\u5458')),
                ('functionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functionary', to=settings.AUTH_USER_MODEL, verbose_name='\u6211\u53f8\u8d1f\u8d23\u4eba')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1Business',
                'verbose_name_plural': '\u4e1a\u52a1Business',
            },
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u57df\u540d')),
                ('use', models.CharField(blank=True, choices=[('0', '\u524d\u7aef\u57df\u540d'), ('1', '\u63a5\u53e3\u57df\u540d'), ('2', '\u540e\u53f0\u57df\u540d')], max_length=64, verbose_name='\u7528\u9014')),
                ('state', models.CharField(blank=True, choices=[('0', '\u542f\u7528'), ('1', '\u672a\u542f\u7528'), ('2', '\u88ab\u5899'), ('3', '\u5f03\u7528')], max_length=64, verbose_name='\u57df\u540d\u72b6\u6001')),
                ('status', models.BooleanField(default=True, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('status_code', models.CharField(blank=True, max_length=64, verbose_name='\u72b6\u6001\u7801')),
                ('address', models.CharField(blank=True, max_length=64, verbose_name='A\u8bb0\u5f55')),
                ('supplier', models.CharField(blank=True, max_length=64, verbose_name='\u4f9b\u5e94\u5546')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Business', verbose_name='\u6240\u5c5e\u4e1a\u52a1')),
            ],
            options={
                'verbose_name': '\u57df\u540dDomainName',
                'verbose_name_plural': '\u57df\u540dDomainName',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('nic_name', models.CharField(blank=True, max_length=32, verbose_name='\u4ee3\u53f7')),
                ('status', models.BooleanField(default=True, verbose_name='\u5e73\u53f0\u72b6\u6001')),
                ('front_db_site', models.CharField(blank=True, max_length=128, verbose_name='\u524d\u7aef\u6570\u636e\u5e93\u63a5\u53e3')),
                ('front_cdn', models.CharField(blank=True, max_length=100, verbose_name='\u524d\u7aefcdn')),
                ('front_high_protection', models.CharField(blank=True, max_length=100, verbose_name='\u524d\u7aef\u9ad8\u9632')),
                ('backend_db_site', models.CharField(blank=True, max_length=128, verbose_name='\u540e\u53f0\u6570\u636e\u5e93\u63a5\u53e3')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u4ecb\u7ecd')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('backend_active_site', models.ManyToManyField(blank=True, related_name='backend_active_site', to='assets.Server', verbose_name='\u540e\u53f0\u52a8\u6001\u8d44\u6e90\u5904\u7406\u7ad9')),
                ('backend_image_site', models.ManyToManyField(blank=True, related_name='backend_image_site', to='assets.Server', verbose_name='\u540e\u53f0\u56fe\u7247\u7ad9')),
                ('backend_proxy', models.ManyToManyField(blank=True, related_name='backend_proxy', to='assets.Server', verbose_name='\u540e\u53f0\u4ee3\u7406')),
                ('backend_station', models.ManyToManyField(blank=True, related_name='backend_station', to='assets.Server', verbose_name='\u540e\u53f0\u6e90\u7ad9')),
                ('front_active_cache', models.ManyToManyField(blank=True, related_name='front_active_cache', to='assets.Server', verbose_name='\u524d\u7aef\u52a8\u6001\u8d44\u6e90\u7f13\u5b58\u7ad9')),
                ('front_active_site', models.ManyToManyField(blank=True, related_name='front_active_site', to='assets.Server', verbose_name='\u524d\u7aef\u52a8\u6001\u8d44\u6e90\u5904\u7406\u7ad9')),
                ('front_download_site', models.ManyToManyField(blank=True, related_name='front_download_site', to='assets.Server', verbose_name='\u524d\u7aef\u4e0b\u8f7d\u7ad9')),
                ('front_image_site', models.ManyToManyField(blank=True, related_name='front_image_site', to='assets.Server', verbose_name='\u524d\u7aef\u56fe\u7247\u7ad9')),
                ('front_proxy', models.ManyToManyField(blank=True, related_name='front_proxy', to='assets.Server', verbose_name='\u524d\u7aef\u4ee3\u7406')),
                ('front_station', models.ManyToManyField(blank=True, related_name='front_station', to='assets.Server', verbose_name='\u524d\u7aef\u6e90\u7ad9')),
                ('third_party_node', models.ManyToManyField(blank=True, related_name='third_party_node', to='assets.Server', verbose_name='\u7b2c\u4e09\u65b9\u53cd\u4ee3\u8282\u70b9')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1Platform',
                'verbose_name_plural': '\u4e1a\u52a1Platform',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Platform', verbose_name='\u5e73\u53f0'),
        ),
        migrations.AddField(
            model_name='bugs',
            name='business',
            field=models.ManyToManyField(blank=True, to='business.Business', verbose_name='\u6d89\u53ca\u4e1a\u52a1'),
        ),
    ]
