# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-04-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainname',
            name='state',
            field=models.CharField(blank=True, choices=[('0', '\u5728\u7528'), ('1', '\u5907\u7528'), ('2', '\u5f03\u7528')], max_length=64, verbose_name='\u57df\u540d\u72b6\u6001'),
        ),
    ]
