# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-09-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180417_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='accelerated_server_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('host', models.TextField(blank=True, verbose_name='\u4e3b\u673a')),
                ('domains', models.TextField(blank=True, null=True, verbose_name='\u57df\u540d')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='\u505c\u7528\u65e5\u671f')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='bug_assigned',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='bug_change_assigned',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='bug_tracker',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='business',
        ),
        migrations.AlterField(
            model_name='business',
            name='platform',
            field=models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u86ee\u725b', '\u86ee\u725b'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('JAVA\u9879\u76ee', 'JAVA\u9879\u76ee'), ('VUE\u86ee\u725b', 'VUE\u86ee\u725b')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.DeleteModel(
            name='Bugs',
        ),
    ]
