# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180915_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='accelerated_domains_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platfrom', models.CharField(blank=True, max_length=64, null=True)),
                ('siteid', models.CharField(blank=True, max_length=10, null=True)),
                ('https', models.BooleanField(default=False)),
                ('ssl_crt_file', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSL_CRT\u6587\u4ef6\u540d')),
                ('ssl_key_file', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSL_KEY\u6587\u4ef6\u540d')),
                ('domains', models.TextField(blank=True, verbose_name='\u57df\u540d')),
            ],
        ),
        migrations.RemoveField(
            model_name='accelerated_server_manager',
            name='host',
        ),
        migrations.RemoveField(
            model_name='accelerated_server_manager',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='accelerated_server_manager',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accelerated_server_manager',
            name='host_main',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='\u4e3bIP'),
        ),
        migrations.AddField(
            model_name='accelerated_server_manager',
            name='host_subordinate',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='\u5907IP'),
        ),
        migrations.AddField(
            model_name='accelerated_server_manager',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accelerated_server_manager',
            name='platfrom',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accelerated_server_manager',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u6dfb\u52a0\u4eba'),
        ),
        migrations.AlterField(
            model_name='accelerated_server_manager',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5230\u671f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u663e\u793a\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='business',
            name='nic_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='SiteID'),
        ),
        migrations.AlterField(
            model_name='business',
            name='platform',
            field=models.CharField(blank=True, choices=[('\u73b0\u91d1\u7f51', '\u73b0\u91d1\u7f51'), ('\u5355\u4e2a\u9879\u76ee', '\u5355\u4e2a\u9879\u76ee'), ('VUE\u86ee\u725b', 'VUE\u86ee\u725b')], max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '\u6b63\u5e38\u8fd0\u8f6c'), ('1', '\u7ef4\u62a4\u5347\u7ea7'), ('2', '\u8fc1\u79fb\u8fc7\u6e21'), ('3', '\u505c\u6b62\u8fd0\u8f6c')], default='0', max_length=100, verbose_name='\u4e1a\u52a1\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='classify',
            field=models.CharField(blank=True, choices=[('test', '\u6d4b\u8bd5'), ('huidu', '\u7070\u5ea6'), ('online', '\u7ebf\u4e0a')], max_length=32, verbose_name='\u73af\u5883'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='supplier',
            field=models.CharField(blank=True, choices=[('\u8fd0\u7ef4', '\u8fd0\u7ef4'), ('\u5de5\u7a0b', '\u5de5\u7a0b'), ('\u7f51\u7ad9', '\u7f51\u7ad9'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=32, verbose_name='\u7ba1\u7406\u8005'),
        ),
        migrations.AddField(
            model_name='accelerated_domains_manager',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accelerate_domain', to='business.accelerated_server_manager'),
        ),
    ]
