# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-07-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opswiki', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='change_date',
            field=models.CharField(default='2017-01-01 12:00:00', max_length=20, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
