# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-26 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('website_normal', '\u73b0\u91d1\u7f51\u6b63\u5e38\u5ba1\u6838'), ('website_urgent', '\u73b0\u91d1\u7f51\u7d27\u6025\u5ba1\u6838')], max_length=25, verbose_name='\u540d\u79f0')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Confile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u53d1\u5e03\u6807\u9898')),
                ('environment', models.CharField(choices=[('production', '\u7ebf\u4e0a\u73af\u5883'), ('test', '\u6d4b\u8bd5\u73af\u5883'), ('huidu', '\u7070\u5ea6\u73af\u5883')], max_length=64, verbose_name='\u90e8\u7f72\u73af\u5883')),
                ('tool_tail', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u4ed3\u5e931\u5c3e\u5df4')),
                ('tool_tail_two', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u4ed3\u5e932\u5c3e\u5df4')),
                ('tool_tail_three', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u4ed3\u5e933\u5c3e\u5df4')),
                ('localhost_dir', models.CharField(blank=True, max_length=128, verbose_name='\u68c0\u51fa\u76ee\u5f551')),
                ('localhost_dir_two', models.CharField(blank=True, max_length=128, verbose_name='\u68c0\u51fa\u76ee\u5f552')),
                ('localhost_dir_three', models.CharField(blank=True, max_length=128, verbose_name='\u68c0\u51fa\u76ee\u5f553')),
                ('specific', models.CharField(blank=True, max_length=128, verbose_name='\u6307\u5b9a\u6587\u4ef6')),
                ('exclude', models.TextField(blank=True, verbose_name='\u6392\u9664\u6587\u4ef6')),
                ('webroot_user', models.CharField(default='www', max_length=32, verbose_name='web\u7528\u6237')),
                ('webroot', models.CharField(max_length=128, verbose_name='web\u76ee\u5f55')),
                ('relaese_dir', models.CharField(max_length=64, verbose_name='\u53d1\u5e03\u7248\u672c\u5e93')),
                ('max_number', models.IntegerField(blank=True, default=10, verbose_name='\u4fdd\u7559\u7248\u672c\u6570')),
                ('server_list', models.TextField(blank=True, verbose_name='\u670d\u52a1\u5668\u5217\u8868')),
                ('pre_deploy', models.TextField(blank=True, verbose_name='\u90e8\u7f72\u524d\u52a8\u4f5c')),
                ('post_deploy', models.TextField(blank=True, verbose_name='\u90e8\u7f72\u540e\u52a8\u4f5c')),
                ('pre_release', models.TextField(blank=True, verbose_name='\u7248\u672c\u62c9\u53d6\u524d\u52a8\u4f5c')),
                ('post_release', models.TextField(blank=True, verbose_name='\u7248\u672c\u62c9\u53d6\u540e\u52a8\u4f5c')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u5173\u8054\u4e1a\u52a1')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u53d1\u5e03\u5c5e\u6027',
                'verbose_name_plural': '\u7248\u672c\u53d1\u5e03\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='deploy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=64, verbose_name='\u53d1\u5e03\u540d\u79f0')),
                ('sit_id', models.CharField(blank=True, max_length=64, verbose_name='\u53d1\u5e03\u4ee3\u53f7')),
                ('branches', models.CharField(blank=True, max_length=64, verbose_name='\u5206\u652f')),
                ('release', models.CharField(blank=True, max_length=64, verbose_name='commit_id')),
                ('release_two', models.CharField(blank=True, max_length=64, verbose_name='commit_id_two')),
                ('release_three', models.CharField(blank=True, max_length=64, verbose_name='commit_id_three')),
                ('check_conf', models.CharField(blank=True, choices=[('\u5df2\u901a\u8fc7', '\u5df2\u901a\u8fc7'), ('\u672a\u901a\u8fc7', '\u672a\u901a\u8fc7')], max_length=32, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('status', models.CharField(blank=True, choices=[('\u5df2\u53d1\u5e03', '\u5df2\u53d1\u5e03'), ('\u672a\u53d1\u5e03', '\u672a\u53d1\u5e03'), ('\u5df2\u56de\u6eda', '\u5df2\u56de\u6eda')], default='\u672a\u53d1\u5e03', max_length=32, verbose_name='\u72b6\u6001')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='\u4e3b\u5e93\u7248\u672c\u53f7')),
                ('tag_two', models.CharField(blank=True, max_length=64, verbose_name='\u526f\u5e93\u7248\u672c\u53f7')),
                ('tag_three', models.CharField(blank=True, max_length=64, verbose_name='\u53c1\u5e93\u7248\u672c\u53f7')),
                ('memo', models.TextField(verbose_name='\u53d1\u5e03\u539f\u56e0')),
                ('execution_time', models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('exist', models.BooleanField(default='False')),
                ('confile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.Confile', verbose_name='\u53d1\u5e03\u9879\u76ee\u914d\u7f6e')),
                ('executive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u7533\u8bf7\u5355',
                'verbose_name_plural': '\u53d1\u5e03\u7533\u8bf7\u5355',
            },
        ),
        migrations.CreateModel(
            name='gengxin_code',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='1001', max_length=45, verbose_name='\u540d\u79f0')),
                ('classify', models.CharField(choices=[('huidu', '\u7070\u5ea6'), ('online', '\u751f\u4ea7'), ('test', '\u6d4b\u8bd5')], default='\u7c7b\u522b', max_length=64, verbose_name='\u7c7b\u578b')),
                ('remoteip', models.TextField(blank=True, default='119.9.81.134', null=True, verbose_name='\u670d\u52a1\u5668ip')),
                ('phone_site', models.BooleanField(default=False, verbose_name='\u624b\u673a\u7aef\u662f\u5426\u53d1\u5e03')),
                ('remotedir', models.CharField(blank=True, default='/data/wwwroot/1001', max_length=45, null=True, verbose_name='\u7ebf\u4e0a\u76ee\u5f55')),
                ('exclude', models.TextField(blank=True, default='Logs/', null=True, verbose_name='\u6392\u9664\u6587\u4ef6')),
                ('rsync_command', models.TextField(blank=True, null=True, verbose_name='\u63a8\u9001\u524d\u547d\u4ee4')),
                ('last_command', models.TextField(blank=True, null=True, verbose_name='\u751f\u6548\u524d\u547d\u4ee4')),
                ('isurgent', models.BooleanField(default=False, verbose_name='\u7d27\u6025\u66f4\u65b0')),
                ('ischeck', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5ba1\u6838')),
                ('period_time', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u66f4\u65b0\u65f6\u6bb5')),
                ('deploy_time', models.IntegerField(default=0, verbose_name='\u66f4\u65b0\u9891\u7387')),
                ('front_domain', models.TextField(blank=True, default='1001.s1119.com', null=True, verbose_name='\u524d\u7aef\u57df\u540d')),
                ('agent_domain', models.TextField(blank=True, default='ag1001.s1119.com', null=True, verbose_name='\u4ee3\u7406\u540e\u53f0\u57df\u540d')),
                ('backend_domain', models.TextField(blank=True, default='ds168.xxx.com\r\nds168.yyy.com', null=True, verbose_name='\u540e\u53f0\u57df\u540d')),
                ('audit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aud', to='automation.AUser', verbose_name='\u6b63\u5e38\u5ba1\u6838\u4eba')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u5173\u8054\u4e1a\u52a1')),
                ('urgent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urg', to='automation.AUser', verbose_name='\u7d27\u6025\u5ba1\u6838\u4eba')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'gengxin_code',
                'verbose_name_plural': 'gengxin_code',
            },
        ),
        migrations.CreateModel(
            name='gengxin_deploy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u79f0')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='\u8fdb\u884c\u72b6\u6001')),
                ('audit_status', models.TextField(blank=True, null=True, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('siteid', models.CharField(blank=True, max_length=10, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('web_reversion', models.CharField(blank=True, max_length=40, null=True)),
                ('pub_reversion', models.CharField(blank=True, max_length=40, null=True)),
                ('con_reversion', models.CharField(blank=True, max_length=40, null=True)),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u53d1\u5e03\u539f\u56e0')),
                ('execution_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('exist', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ed3\u675f')),
                ('code_conf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy', to='automation.gengxin_code', verbose_name='\u914d\u7f6e\u4fe1\u606f')),
                ('executive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-ctime'],
            },
        ),
        migrations.CreateModel(
            name='scriptdeploy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='\u53d1\u5e03\u540d\u79f0')),
                ('sit_id', models.CharField(blank=True, max_length=12, verbose_name='\u53d1\u5e03\u4ee3\u53f7')),
                ('release', models.CharField(max_length=32, verbose_name='\u53c2\u65701')),
                ('release_two', models.CharField(blank=True, max_length=32, verbose_name='\u53c2\u65702')),
                ('release_three', models.CharField(blank=True, max_length=32, verbose_name='\u53c2\u65703')),
                ('memo', models.TextField(verbose_name='\u53d1\u5e03\u539f\u56e0')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('execution_time', models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('check_conf', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('\u5df2\u66f4\u65b0', '\u5df2\u66f4\u65b0'), ('\u672a\u66f4\u65b0', '\u672a\u66f4\u65b0'), ('\u5df2\u53d1\u5e03', '\u5df2\u53d1\u5e03'), ('\u672a\u53d1\u5e03', '\u672a\u53d1\u5e03'), ('\u5df2\u56de\u6eda', '\u5df2\u56de\u6eda')], default='\u672a\u66f4\u65b0', max_length=32, verbose_name='\u72b6\u6001')),
                ('executive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='scriptlog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='\u540d\u79f0')),
                ('memo', models.TextField(blank=True, verbose_name='\u53d1\u5e03\u539f\u56e0')),
                ('command', models.CharField(max_length=128, verbose_name='\u547d\u4ee4')),
                ('result', models.TextField(max_length=128, verbose_name='\u547d\u4ee4\u8f93\u51fa')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sort_time', models.IntegerField(default=0)),
                ('scriptdeploy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.scriptdeploy', verbose_name='\u7528\u6237')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='scriptrepo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='\u53d1\u5e03\u540d\u79f0')),
                ('command', models.CharField(max_length=128, verbose_name='\u547d\u4ee4')),
                ('server_ip', models.GenericIPAddressField(verbose_name='\u811a\u672c\u670d\u52a1\u5668')),
                ('customargs', models.TextField(null=True, verbose_name='\u81ea\u5b9a\u4e49\u53c2\u6570')),
                ('custom_state', models.BooleanField(default=False, verbose_name='\u542f\u7528\u81ea\u5b9a\u4e49\u53c2\u6570')),
                ('memo', models.TextField(null=True, verbose_name='\u4ecb\u7ecd\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('GIT', 'GIT'), ('Subversion', 'Subversion')], max_length=32, verbose_name='\u540d\u79f0')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='\u6807\u9898')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='\u5730\u5740')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='\u7528\u6237')),
                ('passwd', models.CharField(blank=True, max_length=64, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u7ba1\u7406\u5de5\u5177',
                'verbose_name_plural': '\u7248\u672c\u7ba1\u7406\u5de5\u5177',
            },
        ),
        migrations.AddField(
            model_name='confile',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_tool', to='automation.Tools', verbose_name='\u4ee3\u7801\u4ed3\u5e931'),
        ),
        migrations.AddField(
            model_name='confile',
            name='tool_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_tool', to='automation.Tools', verbose_name='\u4ee3\u7801\u4ed3\u5e933'),
        ),
        migrations.AddField(
            model_name='confile',
            name='tool_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_tool', to='automation.Tools', verbose_name='\u4ee3\u7801\u4ed3\u5e932'),
        ),
    ]
