# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-02 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u53d1\u5e03\u6807\u9898')),
                ('environment', models.CharField(choices=[('production', '\u7ebf\u4e0a\u73af\u5883'), ('test', '\u6d4b\u8bd5\u73af\u5883')], max_length=64, verbose_name='\u90e8\u7f72\u73af\u5883')),
                ('localhost_dir', models.CharField(blank=True, max_length=128, verbose_name='code\u68c0\u51fa\u4ed3\u5e93')),
                ('exclude', models.TextField(blank=True, verbose_name='\u6392\u9664\u6587\u4ef6')),
                ('webroot_user', models.CharField(default='www', max_length=32, verbose_name='web\u7528\u6237')),
                ('webroot', models.CharField(max_length=128, verbose_name='web\u76ee\u5f55')),
                ('relaese_dir', models.CharField(max_length=64, verbose_name='\u53d1\u5e03\u7248\u672c\u5e93')),
                ('max_number', models.IntegerField(blank=True, default=10, verbose_name='\u4fdd\u7559\u7248\u672c\u6570')),
                ('server_list', models.TextField(blank=True, verbose_name='\u670d\u52a1\u5668\u5217\u8868')),
                ('pre_deploy', models.TextField(blank=True, verbose_name='\u90e8\u7f72\u524d\u52a8\u4f5c')),
                ('post_deploy', models.TextField(blank=True, verbose_name='\u90e8\u7f72\u540e\u52a8\u4f5c')),
                ('pre_release', models.TextField(blank=True, verbose_name='\u7248\u672c\u62c9\u53d6\u524d\u52a8\u4f5c')),
                ('post_release', models.TextField(blank=True, verbose_name='\u7248\u672c\u62c9\u53d6\u540e\u52a8\u4f5c')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='\u5173\u8054\u4e1a\u52a1')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u53d1\u5e03\u5c5e\u6027',
                'verbose_name_plural': '\u7248\u672c\u53d1\u5e03\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='deploy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('name', models.CharField(max_length=64, verbose_name='\u53d1\u5e03\u540d\u79f0')),
                ('branches', models.CharField(blank=True, max_length=64, verbose_name='\u5206\u652f')),
                ('release', models.CharField(blank=True, max_length=64, verbose_name='commit_id')),
                ('check_conf', models.CharField(blank=True, choices=[('\u5df2\u901a\u8fc7', '\u5df2\u901a\u8fc7'), ('\u672a\u901a\u8fc7', '\u672a\u901a\u8fc7')], max_length=32, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('status', models.CharField(blank=True, choices=[('\u5df2\u53d1\u5e03', '\u5df2\u53d1\u5e03'), ('\u672a\u53d1\u5e03', '\u672a\u53d1\u5e03'), ('\u5df2\u56de\u6eda', '\u5df2\u56de\u6eda')], default='\u672a\u53d1\u5e03', max_length=32, verbose_name='\u72b6\u6001')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='\u6807\u7b7e')),
                ('memo', models.TextField(verbose_name='\u53d1\u5e03\u539f\u56e0')),
                ('execution_time', models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('exist', models.BooleanField(default='False')),
                ('confile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.Confile', verbose_name='\u53d1\u5e03\u9879\u76ee\u914d\u7f6e')),
                ('executive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u7533\u8bf7\u5355',
                'verbose_name_plural': '\u53d1\u5e03\u7533\u8bf7\u5355',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('GIT', 'GIT'), ('Subversion', 'Subversion')], max_length=32, verbose_name='\u540d\u79f0')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='\u6807\u9898')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='\u5730\u5740')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='\u7528\u6237')),
                ('passwd', models.CharField(blank=True, max_length=64, verbose_name='\u5bc6\u7801')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u7ba1\u7406\u5de5\u5177',
                'verbose_name_plural': '\u7248\u672c\u7ba1\u7406\u5de5\u5177',
            },
        ),
        migrations.AddField(
            model_name='confile',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.Tools', verbose_name='\u4ee3\u7801\u4ed3\u5e93'),
        ),
    ]
